# Generated by Django 4.2.1 on 2023-05-11 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softDesk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='author_user',
        ),
    ]
