# Generated by Django 4.2.1 on 2023-05-16 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softDesk', '0003_contributors_issues_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='softDesk.issues'),
        ),
        migrations.AlterField(
            model_name='contributors',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor', to='softDesk.projects'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='L', max_length=45),
        ),
        migrations.AlterField(
            model_name='issues',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projet', to='softDesk.projects'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.CharField(choices=[('I', 'InProgress'), ('T', 'ToDo'), ('C', 'Close')], default='T', max_length=45),
        ),
        migrations.AlterField(
            model_name='issues',
            name='tag',
            field=models.CharField(choices=[('B', 'Bug'), ('T', 'Task'), ('U', 'Upgrade')], max_length=1),
        ),
    ]
