# Generated by Django 4.2.1 on 2023-05-29 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softDesk', '0005_remove_issues_desc_comments_author_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='author_user',
            new_name='author_user_id',
        ),
        migrations.RenameField(
            model_name='issues',
            old_name='author_user',
            new_name='author_user_id',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='author_user',
            new_name='author_user_id',
        ),
    ]
