# Generated by Django 4.2.1 on 2023-06-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softDesk', '0007_rename_assignee_user_issues_assignee_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='author_user_id',
            new_name='author_user',
        ),
        migrations.RenameField(
            model_name='issues',
            old_name='assignee_user_id',
            new_name='assignee_user',
        ),
        migrations.RenameField(
            model_name='issues',
            old_name='author_user_id',
            new_name='author_user',
        ),
        migrations.RenameField(
            model_name='issues',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='author_user_id',
            new_name='author_user',
        ),
    ]
