# Generated by Django 4.2.1 on 2023-06-08 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softDesk', '0008_rename_author_user_id_comments_author_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributor', to='softDesk.projects'),
        ),
    ]
