# Generated by Django 4.2.1 on 2023-06-14 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softDesk', '0011_rename_project_id_contributors_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='issue_id',
            new_name='issue',
        ),
    ]
